将鱼图像数据进行操作，使用numpy知识

# Pandas的数据结构



导入pandas：  
三剑客

In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

### 1、Series

In [2]:
[1,2,3]

[1, 2, 3]

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

Series是一种类似与一维数组的对象，由下面两个部分组成：
- values：一组数据（ndarray类型）
- index：相关的数据索引标签

#### 1）Series的创建

两种创建方式：

(1) 由列表或numpy数组创建

    默认索引为0到N-1的整数型索引

In [4]:
s1 = Series([1,2,3,4,5])

In [5]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [7]:
s2 = Series(n1)
s2

0    1
1    2
2    3
3    4
4    5
dtype: int32

    还可以通过设置index参数指定索引

In [8]:
s3 = Series(data=n1,index=['A','B','C','D','E'])
# s3 = Series(data=n1,index=list('ABCDE'))
s3

A    1
B    2
C    3
D    4
E    5
dtype: int32

特别地，由ndarray创建的是引用，而不是副本。对Series元素的改变也会改变原来的ndarray对象中的元素。（列表没有这种情况）

In [9]:
l1 = np.array([1,2,3,4,5])
s1 = Series(data=l1)
s1[0] = 100
s1

0    100
1      2
2      3
3      4
4      5
dtype: int32

In [10]:
l1

array([100,   2,   3,   4,   5])

(2) 由字典创建

In [11]:
dic = {
    'name':'dancer',
    'oldname':'张学友',
    'age':19,
}

# 字典生成的Series是有序的
s = Series(data=dic)
s

name       dancer
oldname       张学友
age            19
dtype: object

In [12]:
s[2]

19

============================================

练习1：

使用多种方法创建以下Series，命名为s1：  
语文 150   
数学 150   
英语 150   
理综 300   

============================================

In [13]:
data = np.array([150,150,150,300])
index = ['语文','数学','英语','理综']
s1 = Series(data=data,index=index)
s1

语文    150
数学    150
英语    150
理综    300
dtype: int32

#### 2）Series的索引和切片

In [14]:
s1['语文']

150

可以使用中括号取单个索引（此时返回的是元素类型），或者中括号里一个列表取多个索引（此时返回的仍然是一个Series类型）。分为显示索引和隐式索引：

(1) 显式索引：

    - 使用index中的元素作为索引值
    - 使用.loc[]（推荐）

 注意，此时是闭区间

In [15]:
s1[0]

150

In [16]:
s1['语文']

150

In [17]:
s1.loc['语文']

150

In [18]:
s1.loc[['语文','理综']]

语文    150
理综    300
dtype: int32

(2) 隐式索引：

    - 使用整数作为索引值
    - 使用.iloc[]（推荐）

 注意，此时是半开区间

In [19]:
s1.iloc[[0,1]]

语文    150
数学    150
dtype: int32

切片

In [20]:
s = Series(data = np.random.randint(0,100,size=10),index=list('ABCDEFGHIK'))
s

A    92
B    28
C    50
D    82
E    48
F    57
G     4
H    14
I    87
K    14
dtype: int32

In [21]:
# 显式切片 闭区间
s['A':'D']

A    92
B    28
C    50
D    82
dtype: int32

In [22]:
s.loc['A':'F']

A    92
B    28
C    50
D    82
E    48
F    57
dtype: int32

In [23]:
# 隐式切片 闭区间
s[0:4]

A    92
B    28
C    50
D    82
dtype: int32

In [24]:
s.iloc[0:4]

A    92
B    28
C    50
D    82
dtype: int32

============================================

练习2：

使用多种方法对练习1创建的Series s1进行索引和切片：

索引：
数学 150 

切片：
语文 150 
数学 150 
英语 150 

============================================

In [25]:
s1

语文    150
数学    150
英语    150
理综    300
dtype: int32

In [26]:
s1['数学']
s1.loc['数学']
s1[1]
s1.iloc[1]

150

In [27]:
s1['语文':'英语']
s1.loc['语文':'英语']
s1[0:3]
s1.iloc[0:3]

语文    150
数学    150
英语    150
dtype: int32

#### 3）Series的基本概念

可以把Series看成一个定长的有序字典

可以通过shape，size，index,values等得到series的属性

In [28]:
s1.shape

(4,)

In [29]:
s1.size

4

In [30]:
s1.index

Index(['语文', '数学', '英语', '理综'], dtype='object')

In [31]:
type(s1.index)

pandas.core.indexes.base.Index

可以使用head(),tail()分别查看前n个和后n个值

In [33]:
s.head(2)
s.tail(2)

I    87
K    14
dtype: int32

当索引没有对应的值时，可能出现缺失数据显示NaN（not a number）的情况

In [35]:
# Series是索引对齐进行运算
s1 = Series(data = [1,2,3,4],index = list('ABCD'))
s2 = Series(data = [1,2,5,7],index = list('ACDE'))

s1 + s2

A    2.0
B    NaN
C    5.0
D    9.0
E    NaN
dtype: float64

In [36]:
n1 = np.array([1,2,3,4])
n2 = np.array([1,2,5,7])
n1 + n2

array([ 2,  4,  8, 11])

In [37]:
np.nan + 5

nan

In [40]:
# pandas的特性，自动处理None为np.nan
s3 = Series(data = [1,2,3,None,4])
s3

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
dtype: float64

In [41]:
n1 = np.array([1,2,3,np.nan,4])
n1

array([ 1.,  2.,  3., nan,  4.])

series的运算

可以使用pd.isnull()，pd.notnull()，或自带isnull(),notnull()函数检测缺失数据

使用Bool_list访问数组对象

In [42]:
s = Series(np.random.randint(0,100,size=5))
s

0    19
1    98
2    25
3    18
4    85
dtype: int32

In [43]:
bool_list = [True,False,True,False,True]
s[bool_list]

0    19
2    25
4    85
dtype: int32

Series对象本身及其实例都有一个name属性

#### 4）Series的运算

(1) 适用于numpy的数组运算也适用于Series

In [44]:
# 广播机制同样适用于Series
s1 + 10

A    11
B    12
C    13
D    14
dtype: int64

In [45]:
# 需求，创建一个分数列表，求每一个分数占总分数的百分比
score = Series(data=np.random.randint(0,150,size=10))
score

0     86
1    140
2     39
3     65
4    116
5    117
6     52
7     39
8     96
9     38
dtype: int32

In [46]:
score/score.sum()

0    0.109137
1    0.177665
2    0.049492
3    0.082487
4    0.147208
5    0.148477
6    0.065990
7    0.049492
8    0.121827
9    0.048223
dtype: float64

(2) Series之间的运算

- 在运算中自动对齐不同索引的数据
- 如果索引不对应，则补NaN

- 注意：要想保留所有的index，则需要使用.add()函数

In [47]:
s1 = Series(data = [1,2,3,4],index = list('ABCD'))
s2 = Series(data = [1,2,5,7],index = list('ACDE'))

In [48]:
s1.add(s2,fill_value=0)

A    2.0
B    2.0
C    5.0
D    9.0
E    7.0
dtype: float64

# 加减乘除
s1.add()
s1.sub()
s1.mul()
s1.div()

============================================

练习3：

1. 想一想Series运算和ndarray运算的规则有什么不同？

2. 新建另一个索引包含“文综”的Series s2，并与s2进行多种算术操作。

============================================

In [50]:
data1 = np.random.randint(0,150,size=4)
index1 = ['语文','数学','英语','理综']
data2 = np.random.randint(0,150,size=4)
index2 = ['语文','数学','英语','文综']

score1 = Series(data=data1,index=index1)
score2 = Series(data=data2,index=index2)

In [51]:
score1.add(score2,fill_value=0)

数学    213.0
文综     65.0
理综     10.0
英语    177.0
语文    228.0
dtype: float64

### 2、DataFrame

In [52]:
score1.name = '学科分数'

In [53]:
score1

语文    114
数学    128
英语    115
理综     10
Name: 学科分数, dtype: int32

In [54]:
DataFrame(score1)

学科分数
语文   114
数学   128
英语   115
理综    10

DataFrame是一个【表格型】的数据结构，可以看做是【由Series组成的字典】（共用同一个索引）。DataFrame由按一定顺序排列的多列数据组成。设计初衷是将Series的使用场景从一维拓展到多维。DataFrame既有行索引，也有列索引。
- 行索引：index
- 列索引：columns
- 值：values（numpy的二维数组）

In [55]:
data = np.random.randint(0,100,size=(5,5))
index = ['小明','小芳','小玲','大黄','小天才']
columns = ['python','java','php','c','c#']
# 行代表数据样本、对象
# 列代表数据属性、特征

df1 = DataFrame(data=data,index=index,columns=columns)
df1

python  java  php   c  c#
小明       53    54   98  33  54
小芳       87    60   96  98  81
小玲       50    47   62  98  13
大黄       19    78   92  87  45
小天才      78    71   70  43  80

In [56]:
dic = {
    'python':[90,90,50,30,25],
    'java':[90,90,25,50,30],
    'php':[90,90,80,80,80],
    'c':[0,0,100,100,100],
    'c#':[0,0,100,100,100]
}

df2 = DataFrame(data=dic)
df2.index = ['dancer','mery','tom','jack','rose']
df2

python  java  php    c   c#
dancer      90    90   90    0    0
mery        90    90   90    0    0
tom         50    25   80  100  100
jack        30    50   80  100  100
rose        25    30   80  100  100

#### 1）DataFrame的创建
最常用的方法是传递一个字典来创建。DataFrame以字典的键作为每一【列】的名称，以字典的值（一个数组）作为每一列。

此外，DataFrame会自动加上每一行的索引（和Series一样）。

同Series一样，若传入的列与字典的键不匹配，则相应的值为NaN。


DataFrame属性：values、columns、index、shape

In [57]:
data = np.random.randint(0,100,size=(5,5))
index = ['小明','小芳','小玲','大黄','小天才']
columns = ['python','java','php','c','c#']
# 行代表数据样本、对象
# 列代表数据属性、特征

df1 = DataFrame(data=data,index=index,columns=columns)
df1

python  java  php   c  c#
小明        0    75   56  88  16
小芳       11    50   34   2  34
小玲       12    58   17  51   3
大黄       65    70   81  87  67
小天才      69    32   70  82  98

In [58]:
df1.values

array([[ 0, 75, 56, 88, 16],
       [11, 50, 34,  2, 34],
       [12, 58, 17, 51,  3],
       [65, 70, 81, 87, 67],
       [69, 32, 70, 82, 98]])

In [59]:
df1.index

Index(['小明', '小芳', '小玲', '大黄', '小天才'], dtype='object')

In [60]:
df1.columns = ['a','b','c','d','e']

In [61]:
# index\columns都可以赋值
# values只读的，不能赋值
value = np.random.randint(100,200,size=(5,5))
df1.values = value
df1

D:\software\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  after removing the cwd from sys.path.


AttributeError: can't set attribute

In [63]:
df1.shape

(5, 5)

============================================

练习4：

根据以下考试成绩表，创建一个DataFrame，命名为df：
```
    张三  李四
语文 150  0
数学 150  0
英语 150  0
理综 300  0
```

============================================

In [64]:
# data\index\columns
data = np.array([[150,0],[150,0],[150,0],[300,0]])
index = ['语文','数学','英语','理综']
columns = ['张三','李四']
df = DataFrame(data=data,index=index,columns=columns)

# 字典
dic = {
    '张三':[150,150,150,300],
    '李四':[0,0,0,0]
}
df1 = DataFrame(data=dic,index=index)
display(df1,df)

张三  李四
语文  150   0
数学  150   0
英语  150   0
理综  300   0

张三  李四
语文  150   0
数学  150   0
英语  150   0
理综  300   0

#### 2）DataFrame的索引

(1) 对列进行索引

    - 通过类似字典的方式
    - 通过属性的方式

 可以将DataFrame的列获取为一个Series。返回的Series拥有原DataFrame相同的索引，且name属性也已经设置好了，就是相应的列名。

In [65]:
dic = {
    'name':['dancer','tom','lucy','jack','rose'],
    'age':[19,18,30,25,18],
    'address':['beijing','shanghai','guangzhou','shenzhen','haerbin']
}

df = DataFrame(data=dic)
df

name  age    address
0  dancer   19    beijing
1     tom   18   shanghai
2    lucy   30  guangzhou
3    jack   25   shenzhen
4    rose   18    haerbin

In [66]:
# # 不可以这样进行隐式索引访问
# df[0]

In [67]:
# 对列进行索引，参数必须是列索引标签
df['address']

0      beijing
1     shanghai
2    guangzhou
3     shenzhen
4      haerbin
Name: address, dtype: object

In [68]:
# 使用类似属性的方式访问一列
df.address

0      beijing
1     shanghai
2    guangzhou
3     shenzhen
4      haerbin
Name: address, dtype: object

(2) 对行进行索引

    - 使用.ix[]来进行行索引
    - 使用.loc[]加index来进行行索引
    - 使用.iloc[]加整数来进行行索引
    
 同样返回一个Series，index为原来的columns。

In [69]:
# 以表格中的某一列重新设置行索引，set_index（标签名）
df1 = df.set_index(keys=['name'])

In [70]:
df1

age    address
name                  
dancer   19    beijing
tom      18   shanghai
lucy     30  guangzhou
jack     25   shenzhen
rose     18    haerbin

In [71]:
df1.loc['dancer']

age             19
address    beijing
Name: dancer, dtype: object

In [72]:
df.loc[1]

name            tom
age              18
address    shanghai
Name: 1, dtype: object

In [73]:
df1

age    address
name                  
dancer   19    beijing
tom      18   shanghai
lucy     30  guangzhou
jack     25   shenzhen
rose     18    haerbin

In [74]:
# 隐式索引访问行
df1.ix[0]

D:\software\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


age             19
address    beijing
Name: dancer, dtype: object

(3) 对元素索引的方法
    - 使用列索引
    - 使用行索引(iloc[3,1]相当于两个参数;iloc[[3,3]] 里面的[3,3]看做一个参数)
    - 使用values属性（二维numpy数组）

In [75]:
df

name  age    address
0  dancer   19    beijing
1     tom   18   shanghai
2    lucy   30  guangzhou
3    jack   25   shenzhen
4    rose   18    haerbin

In [76]:
df.name[1]

'tom'

In [77]:
df.loc[1]['name']

'tom'

In [78]:
df.loc[1,'name']

'tom'

In [79]:
# 获取索引为1的行和索引为2的列对应的值
df.iloc[1,2]

'shanghai'

In [80]:
# 获取多行 索引为1和2的行
df.iloc[[1,2]]

name  age    address
1   tom   18   shanghai
2  lucy   30  guangzhou

In [81]:
# 获取多列
df[['address','name']]

address    name
0    beijing  dancer
1   shanghai     tom
2  guangzhou    lucy
3   shenzhen    jack
4    haerbin    rose

In [83]:
# 【重点】
# 获取一列  df[列标签]              获取多列[[列标签1，列标签2]]
# 获取一行  df.loc[行标签]          获取多行 df.loc[[行标签1，行标签2]]
# 获取元素  df.loc[行标签，列标签]

### 切片

In [83]:
# 行索引
df[0:2]

name  age   address
0  dancer   19   beijing
1     tom   18  shanghai

In [84]:

# 隐式索引
df.iloc[0:2]

name  age   address
0  dancer   19   beijing
1     tom   18  shanghai

In [87]:
df

name  age    address
0  dancer   19    beijing
1     tom   18   shanghai
2    lucy   30  guangzhou
3    jack   25   shenzhen
4    rose   18    haerbin

In [97]:
df.loc[:,'age':'address']

age    address
0   19    beijing
1   18   shanghai
2   30  guangzhou
3   25   shenzhen
4   18    haerbin

In [91]:
# 列切片

df.iloc[:,0:3]

name  age    address
0  dancer   19    beijing
1     tom   18   shanghai
2    lucy   30  guangzhou
3    jack   25   shenzhen
4    rose   18    haerbin

【注意】
直接用中括号时：
- 索引表示的是列索引
- 切片表示的是行切片

============================================

练习5：

使用多种方法对df进行索引和切片，并比较其中的区别

============================================

In [98]:
data = np.random.randint(0,150,size=(5,5))
index = list('ABCDE')
columns = ['python','Java','C','OC','PHP']
df = DataFrame(data=data,index=index,columns=columns)
df

python  Java    C   OC  PHP
A     101    63  114    7  136
B      67    40    5   60   59
C      29    61   78  117   31
D      27    76   27   21   21
E     117   129    9   54   53

In [101]:
df[['Java','C']]
df.loc[:,'Java':'C']
df.iloc[:,1:3]

Java    C
A    63  114
B    40    5
C    61   78
D    76   27
E   129    9

In [102]:
df.loc['B':'C']
df['B':'C']
df.iloc[1:3]
df.loc[['B','C']]

python  Java   C   OC  PHP
B      67    40   5   60   59
C      29    61  78  117   31

In [103]:
df['Java']['A']
df.loc['A']['Java']
df.loc['A','Java']

63

In [104]:
df['PHP']
df.PHP

A    136
B     59
C     31
D     21
E     53
Name: PHP, dtype: int32

In [105]:
df.loc['B']
df.iloc[1]
df.loc['B':'B']

python  Java  C  OC  PHP
B      67    40  5  60   59

#### 3）DataFrame的运算

numpy运算 聚合  np.nansum()
广播 空值

Sereis  s.add
索引对齐

（1） DataFrame之间的运算

同Series一样：

- 在运算中自动对齐相同索引的数据
- 如果索引不对应，则补NaN

In [108]:
data = np.random.randint(0,100,size=(5,5))
index = list('ABCDE')
columns = list('甲乙丙丁戊')

df1 = DataFrame(data=data,index=index,columns=columns)
df1

甲   乙   丙   丁   戊
A   6   4  42  11  14
B  54  45  95  74  98
C  64  46   6  82  34
D  44  31  88   6  85
E  62  52  87  56  50

In [109]:
data2 = np.random.randint(100,200,size=(3,3))
index2 = list('ABC')
columns2 = list('甲乙寅')

df2 = DataFrame(data=data2,index=index2,columns=columns2)
df2

甲    乙    寅
A  153  161  178
B  178  160  192
C  160  169  177

In [110]:
df1 + df2

丁   丙      乙   寅   戊      甲
A NaN NaN  165.0 NaN NaN  159.0
B NaN NaN  205.0 NaN NaN  232.0
C NaN NaN  215.0 NaN NaN  224.0
D NaN NaN    NaN NaN NaN    NaN
E NaN NaN    NaN NaN NaN    NaN

In [111]:
df1.add(df2,fill_value=0)

丁     丙      乙      寅     戊      甲
A  11.0  42.0  165.0  178.0  14.0  159.0
B  74.0  95.0  205.0  192.0  98.0  232.0
C  82.0   6.0  215.0  177.0  34.0  224.0
D   6.0  88.0   31.0    NaN  85.0   44.0
E  56.0  87.0   52.0    NaN  50.0   62.0

创建DataFrame df1 不同人员的各科目成绩，月考一

创建DataFrame df2 不同人员的各科目成绩，月考二  
有新学生转入

下面是Python 操作符与pandas操作函数的对应表：

| Python Operator | Pandas Method(s)                      |
|-----------------|---------------------------------------|
| ``+``           | ``add()``                             |
| ``-``           | ``sub()``, ``subtract()``             |
| ``*``           | ``mul()``, ``multiply()``             |
| ``/``           | ``truediv()``, ``div()``, ``divide()``|
| ``//``          | ``floordiv()``                        |
| ``%``           | ``mod()``                             |
| ``**``          | ``pow()``                             |


（2） Series与DataFrame之间的运算

【重要】

- 使用Python操作符：以行为单位操作（参数必须是行），对所有行都有效。（类似于numpy中二维数组与一维数组的运算，但可能出现NaN）

- 使用pandas操作函数：

        axis=0：以列为单位操作（参数必须是列），对所有列都有效。
        axis=1：以行为单位操作（参数必须是行），对所有行都有效。

In [112]:
s1 = Series(data=np.random.randint(0,100,size=5),index=list('ABCDE'))
df1 = DataFrame(data = np.random.randint(0,100,size=(5,5)),index=list('BCDEF'),columns=list('甲乙丙丁戊'))
display(s1,df1)

A    57
B    38
C    92
D    99
E    16
dtype: int32

甲   乙   丙   丁   戊
B  29  54  68  76  68
C  88  22  34   7  85
D  85  67  56   0  50
E  14  83   5  55  22
F  91  31  79  49  73

In [113]:
df1 + s1

A   B   C   D   E   丁   丙   乙   戊   甲
B NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
C NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
D NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
E NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
F NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

In [115]:
display(df1.shape,s1.shape)

(5, 5)

(5,)

In [114]:
# fill_value在df和series之间运算时，不能使用
df1.add(s1,axis=0)

甲      乙      丙      丁      戊
A    NaN    NaN    NaN    NaN    NaN
B   67.0   92.0  106.0  114.0  106.0
C  180.0  114.0  126.0   99.0  177.0
D  184.0  166.0  155.0   99.0  149.0
E   30.0   99.0   21.0   71.0   38.0
F    NaN    NaN    NaN    NaN    NaN

  axis=0（0 == index 行）：以列为单位操作（参数必须是列），对所有列都有效。
  axis=1（1 == columns 列）：以行为单位操作（参数必须是行），对所有行都有效。

【注意】fill_value在df和series之间运算时，不能使用

============================================

练习6：

1. 假设ddd是期中考试成绩，ddd2是期末考试成绩，请自由创建ddd2，并将其与ddd相加，求期中期末平均值。

2. 假设张三期中考试数学被发现作弊，要记为0分，如何实现？

3. 李四因为举报张三作弊立功，期中考试所有科目加100分，如何实现？

4. 后来老师发现有一道题出错了，为了安抚学生情绪，给每位学生每个科目都加10分，如何实现？

============================================

In [117]:
score1 = DataFrame(data=np.random.randint(0,100,size=(3,3)),index=['dancer','tom','jack'],columns=['python','c','java'])
score2 = DataFrame(data=np.random.randint(0,100,size=(3,3)),index=['dancer','tom','jack'],columns=['python','c','java'])
display(score1,score2)

python   c  java
dancer      90  76    69
tom         86  78    24
jack        86  81    21

python   c  java
dancer      26  83    45
tom          3  75    91
jack        60  85    53

In [118]:
mean = (score1 + score2)/2
display(mean)

python     c  java
dancer    58.0  79.5  57.0
tom       44.5  76.5  57.5
jack      73.0  83.0  37.0

In [119]:
score1.loc['dancer','c'] = 0
score1

python   c  java
dancer      90   0    69
tom         86  78    24
jack        86  81    21

In [120]:
score1.loc['tom'] += 100

In [121]:
score1

python    c  java
dancer      90    0    69
tom        186  178   124
jack        86   81    21

In [122]:
score1 += 10
score1

python    c  java
dancer     100   10    79
tom        196  188   134
jack        96   91    31