In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame


In [2]:
obj=Series([1,2,3,4])
print(obj)

0    1
1    2
2    3
3    4
dtype: int64


In [3]:
obj2=Series([1,2,3,4],index=['a','b','c','d'])

In [4]:
print(obj2)

a    1
b    2
c    3
d    4
dtype: int64


In [5]:
a=np.array([1,2,3])
obj=Series(a)
obj

0    1
1    2
2    3
dtype: int64

In [6]:
obj[0]=0

In [7]:
obj

0    0
1    2
2    3
dtype: int64

In [8]:
print a


SyntaxError: Missing parentheses in call to 'print' (<ipython-input-8-da1608c9d425>, line 1)

In [9]:
print(a)

[0 2 3]


In [10]:
obj=Series({'a':1,'b':2})

In [11]:
print(obj)

a    1
b    2
dtype: int64


In [12]:
a=Series({"语文":150,"数学":150,"英语":150, "理综":300})
print(a)

语文    150
数学    150
英语    150
理综    300
dtype: int64


In [14]:
a=Series([150,150,150,300],index=["语文","数学","英语","理综"])
print(a)

语文    150
数学    150
英语    150
理综    300
dtype: int64


In [15]:
obj = Series({'a':10,'b':12,'c':17})
obj.loc['a']

10

In [20]:
obj['a':'z']

a    10
b    12
c    17
dtype: int64

In [21]:
obj[0:1]

a    10
dtype: int64

In [22]:
obj.iloc[0]

10

In [26]:
obj.iloc[0:2]

a    10
b    12
dtype: int64

In [27]:
obj.iloc[1:2]

b    12
dtype: int64

In [29]:
print(a.loc['数学'])
print(a[0])
print(a)
print(a[0:1])


150
150
语文    150
数学    150
英语    150
理综    300
dtype: int64
语文    150
dtype: int64


In [33]:
obj.shape



(3,)

In [32]:
obj.values

array([10, 12, 17])

In [34]:
obj.size

3

In [40]:
obj.head(2)


a    10
b    12
dtype: int64

In [39]:
obj.tail(1)


c    17
dtype: int64

In [45]:
obj.loc['c']

17

In [53]:
obj = Series([10,4,np.nan])
#判断Series是否为不为null，为null返回false
print(obj)
notnull = pd.isnull(obj)
print(notnull)
#如果为false将空值设为0
for i,d in enumerate(notnull):
    if d ==1:
        obj[i] = 0
print(obj)

0    10.0
1     4.0
2     NaN
dtype: float64
0    False
1    False
2     True
dtype: bool
0    10.0
1     4.0
2     0.0
dtype: float64


In [54]:
obj.name='123'
print(obj)
Series.name = "Hello World"
print(Series.name)

0    10.0
1     4.0
2     0.0
Name: 123, dtype: float64
Hello World


In [55]:
A = pd.Series([2,4,6],index=[0,1,2])
B = pd.Series([1,3,5],index=[1,2,3])
display(A,B)

0    2
1    4
2    6
dtype: int64

1    1
2    3
3    5
dtype: int64

In [57]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [58]:
import pandas as ps
from pandas import Series,DataFrame
data = {'color':['blue','green','yellow','red','white'],
       'object':['ball','pen','pencil','paper','mug'],
       'price':[1.2,1.0,0.6,0.9,1.7]}
frame = DataFrame(data,columns=['color','object','price','weight'],
                 index = ['one','two','three','four','five'])
frame

color  object  price weight
one      blue    ball    1.2    NaN
two     green     pen    1.0    NaN
three  yellow  pencil    0.6    NaN
four      red   paper    0.9    NaN
five    white     mug    1.7    NaN

In [59]:
# dic = {'张三':[150,150,150,300],"李四":[0,0,0,0]}
# ddd = DataFrame(dic,index=['语文','数学','英语','理综'])
# ddd
import numpy as np
dic = {'张三':[150,150,150,147],'李四':[0,0,0,0]}
ind = np.array(['语文','数学','英语','编程'])
ddd = DataFrame(dic,index=ind)
ddd

张三  李四
语文  150   0
数学  150   0
英语  150   0
编程  147   0

In [65]:
ddd["李四"]

语文    0
数学    0
英语    0
编程    0
Name: 李四, dtype: int64

In [67]:
ddd[["张三","李四"]]

张三  李四
语文  150   0
数学  150   0
英语  150   0
编程  147   0

In [73]:
ddd.loc[:,"张三":"李四"]

张三  李四
语文  150   0
数学  150   0
英语  150   0
编程  147   0

In [69]:
print(frame)
frame['color']

        color  object  price weight
one      blue    ball    1.2    NaN
two     green     pen    1.0    NaN
three  yellow  pencil    0.6    NaN
four      red   paper    0.9    NaN
five    white     mug    1.7    NaN


one        blue
two       green
three    yellow
four        red
five      white
Name: color, dtype: object

In [70]:
frame.color

one        blue
two       green
three    yellow
four        red
five      white
Name: color, dtype: object

In [76]:
frame


color  object  price weight
one      blue    ball    1.2    NaN
two     green     pen    1.0    NaN
three  yellow  pencil    0.6    NaN
four      red   paper    0.9    NaN
five    white     mug    1.7    NaN

In [77]:
frame.loc['one']

color     blue
object    ball
price      1.2
weight     NaN
Name: one, dtype: object

In [78]:
frame.iloc[0:10]


color  object  price weight
one      blue    ball    1.2    NaN
two     green     pen    1.0    NaN
three  yellow  pencil    0.6    NaN
four      red   paper    0.9    NaN
five    white     mug    1.7    NaN

In [82]:
frame.loc['one':'four']

color  object  price weight
one      blue    ball    1.2    NaN
two     green     pen    1.0    NaN
three  yellow  pencil    0.6    NaN
four      red   paper    0.9    NaN

In [83]:

print(frame)
print("使用列索引")
print(frame['color']['one'])
print(frame.color['one'])
print("使用行索引")
print(frame.ix['one']['color'])
print(frame.loc['one','color'])
print(frame.iloc[0][0:2])
print("使用values属性")
print(frame.values[[0][0]])
print(frame.values[0][1:3])


        color  object  price weight
one      blue    ball    1.2    NaN
two     green     pen    1.0    NaN
three  yellow  pencil    0.6    NaN
four      red   paper    0.9    NaN
five    white     mug    1.7    NaN
使用列索引
blue
blue
使用行索引
blue
blue
color     blue
object    ball
Name: one, dtype: object
使用values属性
['blue' 'ball' 1.2 nan]
['ball' 1.2]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:7: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  import sys


In [85]:
print(frame['color'])


one        blue
two       green
three    yellow
four        red
five      white
Name: color, dtype: object


In [86]:
frame['one':'two']


color object  price weight
one   blue   ball    1.2    NaN
two  green    pen    1.0    NaN

In [98]:
A = DataFrame(np.random.randint(0,20,(2,2)),columns = list('ab'))
A

a   b
0  19   7
1   9  13

In [99]:
B = DataFrame(np.random.randint(0,10,(3,3)),columns = list('abc'))
B

a  b  c
0  4  8  6
1  2  2  9
2  9  5  8

In [100]:
A+B

a     b   c
0  23.0  15.0 NaN
1  11.0  15.0 NaN
2   NaN   NaN NaN

In [101]:
A.add(B,fill_value=0)


a     b    c
0  23.0  15.0  6.0
1  11.0  15.0  9.0
2   9.0   5.0  8.0

In [102]:
A-B

a     b   c
0  15.0  -1.0 NaN
1   7.0  11.0 NaN
2   NaN   NaN NaN

In [103]:

A = np.random.randint(10,size = (3,4))
A

array([[7, 9, 5, 1],
       [4, 3, 8, 0],
       [5, 4, 4, 9]])

In [104]:

B = np.random.randint(10,size = (4))
B

array([1, 4, 6, 5])

In [105]:
A-B

array([[ 6,  5, -1, -4],
       [ 3, -1,  2, -5],
       [ 4,  0, -2,  4]])

In [107]:
A = np.random.randint(10,size = (3,4))
df = DataFrame(A,columns = list("QWER"))
df


Q  W  E  R
0  8  2  8  1
1  9  2  3  3
2  2  0  0  2

In [112]:
display(df)
display(df.iloc[0:2])
display(df.iloc[0,::2])
df.sub(df.iloc[0,::2],axis = 1)


Q  W  E  R
0  8  2  8  1
1  9  2  3  3
2  2  0  0  2

Q  W  E  R
0  8  2  8  1
1  9  2  3  3

Q    8
E    8
Name: 0, dtype: int64

E    Q   R   W
0  0.0  0.0 NaN NaN
1 -5.0  1.0 NaN NaN
2 -8.0 -6.0 NaN NaN

In [111]:
display(df)
display(df['Q'])
df.sub(df['Q'],axis = 0)


Q  W  E  R
0  8  2  8  1
1  9  2  3  3
2  2  0  0  2

0    8
1    9
2    2
Name: Q, dtype: int64

Q  W  E  R
0  0 -6  0 -7
1  0 -7 -6 -6
2  0 -2 -2  0

In [113]:
%timeit sum_int = np.arange(1E6,dtype=int).sum()
%timeit sum_int = np.arange(1E6,dtype=float).sum()
%timeit sum_int = np.arange(1E6,dtype=object).sum()

3.72 ms ± 292 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.79 ms ± 240 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
86.4 ms ± 2.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [114]:
np.nan

nan

In [116]:
a = Series([1,np.nan,2,None])
a

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [117]:
a = Series([1,np.nan,2,None])
a

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [119]:
a.isnull()


0    False
1     True
2    False
3     True
dtype: bool

In [121]:
a[a.notnull()]


0    1.0
2    2.0
dtype: float64

In [122]:
df.dropna(axis=0)


Q  W  E  R
0  8  2  8  1
1  9  2  3  3
2  2  0  0  2

In [124]:
df = DataFrame([[1,np.nan,2],
               [2,3,5],
               [np.nan,4,6]],columns = ['昨天','今天','明天'],index = ['吃饭','睡觉','过家家'])
df

昨天   今天  明天
吃饭   1.0  NaN   2
睡觉   2.0  3.0   5
过家家  NaN  4.0   6

In [125]:
df.dropna()


昨天   今天  明天
睡觉  2.0  3.0   5

In [126]:
df.dropna(axis=1)


明天
吃饭    2
睡觉    5
过家家   6

In [127]:
df.dropna(axis=0)


昨天   今天  明天
睡觉  2.0  3.0   5

In [128]:
df[3]=np.nan
display(df)
df.dropna(axis='index',how='all')


昨天   今天  明天   3
吃饭   1.0  NaN   2 NaN
睡觉   2.0  3.0   5 NaN
过家家  NaN  4.0   6 NaN

昨天   今天  明天   3
吃饭   1.0  NaN   2 NaN
睡觉   2.0  3.0   5 NaN
过家家  NaN  4.0   6 NaN

In [132]:
data = Series([1,np.nan,2,None,4],index = list('abcdf'))
data

a    1.0
b    NaN
c    2.0
d    NaN
f    4.0
dtype: float64

In [133]:
data.fillna(10)


a     1.0
b    10.0
c     2.0
d    10.0
f     4.0
dtype: float64

In [134]:
display(data)
data.fillna(method='ffill')

a    1.0
b    NaN
c    2.0
d    NaN
f    4.0
dtype: float64

a    1.0
b    1.0
c    2.0
d    2.0
f    4.0
dtype: float64

In [136]:
display(df)
df.fillna(method='ffill',axis=0)#行


昨天   今天  明天   3
吃饭   1.0  NaN   2 NaN
睡觉   2.0  3.0   5 NaN
过家家  NaN  4.0   6 NaN

昨天   今天  明天   3
吃饭   1.0  NaN   2 NaN
睡觉   2.0  3.0   5 NaN
过家家  2.0  4.0   6 NaN

In [138]:
display(data)
data.fillna(method='bfill')


a    1.0
b    NaN
c    2.0
d    NaN
f    4.0
dtype: float64

a    1.0
b    2.0
c    2.0
d    4.0
f    4.0
dtype: float64

In [139]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
df = DataFrame(index = ['吃饭','睡觉','写代码','人生'],columns = ["今天","昨天","明天"],
               data = np.random.randint(0,1024,(4,3)),dtype="object")
display(df)
print(df.loc['睡觉'])
df.loc["睡觉"][::2] =np.nan
df['今天'][::2] = np.nan
display(df)
df.fillna(method='bfill',axis=1)#列


今天   昨天   明天
吃饭   848  561  286
睡觉   613  555  774
写代码  448  602  451
人生   349  916  220

今天    613
昨天    555
明天    774
Name: 睡觉, dtype: object


今天   昨天   明天
吃饭   NaN  561  286
睡觉   NaN  555  NaN
写代码  NaN  602  451
人生   349  916  220

今天   昨天     明天
吃饭   561  561  286.0
睡觉   555  555    NaN
写代码  602  602  451.0
人生   349  916  220.0